# Generated by Django 3.2 on 2023-02-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('default_street_address1', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('default_nationality', django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=50)),
                ('cc_number', models.CharField(default=None, max_length=19)),
                ('cc_expiry', models.DateField(default=None)),
                ('cc_code', models.CharField(default=None, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
