# Generated by Django 3.2 on 2023-01-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
