# Generated by Django 3.2 on 2022-12-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_cars_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackday',
            fields=[
                ('layout', models.IntegerField(choices=[(2, 'Indy'), (1, 'National'), (0, 'GP')], default=0)),
                ('date', models.DateField()),
                ('db_limit', models.BooleanField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('car_hire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.cars')),
                ('base_trackday_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TrackdayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_or_half_day', models.BooleanField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('additional_drivers', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('helmet_hire', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('tuition', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('hospitality_packs', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('paddock_hire', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('trackday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackdays.trackday')),
            ],
        ),
    ]
