# Generated by Django 3.2 on 2023-02-12 17:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('itinerary', models.TextField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Trackday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.IntegerField(choices=[(1, 'National'), (2, 'Indy'), (0, 'GP')], default=0)),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(default=None, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('db_limit', models.BooleanField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('availability', models.IntegerField(default=30)),
                ('base_trackday_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TrackdayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_request', models.DateField(blank=True, null=True)),
                ('full_or_half_day', models.IntegerField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('number_of_spaces', models.IntegerField(blank=True, null=True)),
                ('hospitality', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('pitlanes', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('db_limit', models.IntegerField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('car_hire_required', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(choices=[(0, 'Bronze'), (2, 'Gold'), (1, 'Silver')], default=None)),
                ('description', models.TextField(max_length=1500)),
                ('itinerary', models.TextField(max_length=1500)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Tuition',
            },
        ),
        migrations.CreateModel(
            name='TrackdayBooking',
            fields=[
                ('car_hire', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.cars')),
                ('full_or_half_day', models.IntegerField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('additional_drivers', models.PositiveIntegerField(default=0)),
                ('helmet_hire', models.PositiveIntegerField(default=0)),
                ('tuition', models.PositiveIntegerField(default=0)),
                ('paddock_hire', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('trackday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackdays.trackday')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
