# Generated by Django 3.2 on 2022-12-27 20:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_alter_cars_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('itinerary', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Trackday',
            fields=[
                ('layout', models.IntegerField(choices=[(0, 'GP'), (1, 'National'), (2, 'Indy')], default=0)),
                ('date', models.DateField(default=None, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('db_limit', models.BooleanField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('car_hire', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.cars')),
                ('base_trackday_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TrackdayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_request', models.DateField(blank=True, null=True)),
                ('full_or_half_day', models.BooleanField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('number_of_spaces', models.IntegerField(blank=True, null=True)),
                ('hospitality', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('pitlanes', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('db_limit', models.BooleanField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('car_hire_required', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold')], default=None)),
                ('description', models.CharField(max_length=300)),
                ('itinerary', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Tuition',
            },
        ),
        migrations.CreateModel(
            name='TrackdayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_or_half_day', models.BooleanField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('additional_drivers', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('helmet_hire', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('tuition', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('hospitality_packs', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('paddock_hire', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('trackday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackdays.trackday')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trackday',
            constraint=models.UniqueConstraint(fields=('layout', 'date'), name='unique_trackday'),
        ),
    ]
