# Generated by Django 3.2 on 2022-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(1, 'National'), (0, 'GP'), (2, 'Indy')], default=0),
        ),
    ]
