# Generated by Django 3.2 on 2022-12-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackday',
            name='availability',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(2, 'Indy'), (1, 'National'), (0, 'GP')], default=0),
        ),
    ]
