# Generated by Django 3.2 on 2022-12-21 23:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_variant'),
        ('trackdays', '0002_alter_trackday_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackday',
            name='car_hire',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='trackday',
            name='date',
            field=models.DateField(default=None, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(0, 'GP'), (1, 'National'), (2, 'Indy')], default=0),
        ),
        migrations.AddConstraint(
            model_name='trackday',
            constraint=models.UniqueConstraint(fields=('layout', 'date'), name='unique_trackday'),
        ),
    ]
