# Generated by Django 3.2 on 2022-12-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0003_auto_20221221_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(1, 'National'), (0, 'GP'), (2, 'Indy')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='additional_drivers',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='helmet_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='hospitality_packs',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='paddock_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='tuition',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
