# Generated by Django 3.2 on 2022-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0003_auto_20221227_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='itinerary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(0, 'GP'), (1, 'National'), (2, 'Indy')], default=0),
        ),
    ]
