# Generated by Django 3.2 on 2022-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0003_auto_20221230_1607'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackday',
            name='unique_trackday',
        ),
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(2, 'Indy'), (0, 'GP'), (1, 'National')], default=0),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='level',
            field=models.IntegerField(choices=[(0, 'Bronze'), (2, 'Gold'), (1, 'Silver')], default=None),
        ),
    ]
