# Generated by Django 3.2 on 2022-12-23 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0005_experiences_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackdayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_request', models.DateField(blank=True, null=True)),
                ('full_or_half_day', models.BooleanField(choices=[(0, 'Half-day'), (1, 'Full-day')], default=0)),
                ('number_of_spaces', models.IntegerField(blank=True, null=True)),
                ('hospitality', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('pitlanes', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('db_limit', models.BooleanField(choices=[(0, '98db'), (1, '105db')], default=0)),
                ('car_hire_required', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(0, 'GP'), (1, 'National'), (2, 'Indy')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='additional_drivers',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='helmet_hire',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='hospitality_packs',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='paddock_hire',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='tuition',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='level',
            field=models.IntegerField(choices=[(1, 'Silver'), (0, 'Bronze'), (2, 'Gold')], default=None),
        ),
    ]
