# Generated by Django 3.2 on 2023-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0005_auto_20230103_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdaybooking',
            name='additional_drivers',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='helmet_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='hospitality_packs',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='paddock_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='tuition',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='car_hire_required',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='hospitality',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='pitlanes',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='level',
            field=models.IntegerField(choices=[(0, 'Bronze'), (2, 'Gold'), (1, 'Silver')], default=None),
        ),
    ]
