# Generated by Django 3.2 on 2023-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0006_auto_20230103_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='image',
            new_name='large_image',
        ),
        migrations.AddField(
            model_name='tuition',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='level',
            field=models.IntegerField(choices=[(2, 'Gold'), (1, 'Silver'), (0, 'Bronze')], default=None),
        ),
    ]
