# Generated by Django 3.2 on 2023-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0007_auto_20230103_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(1, 'National'), (0, 'GP'), (2, 'Indy')], default=0),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='itinerary',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='level',
            field=models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold')], default=None),
        ),
    ]
