# Generated by Django 3.2 on 2022-12-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackdays', '0007_auto_20221223_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackday',
            name='layout',
            field=models.IntegerField(choices=[(0, 'GP'), (2, 'Indy'), (1, 'National')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='additional_drivers',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='helmet_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='hospitality_packs',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='paddock_hire',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdaybooking',
            name='tuition',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='car_hire_required',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='hospitality',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trackdayrequest',
            name='pitlanes',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
