# Generated by Django 3.2 on 2022-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('query_type', models.CharField(choices=[(0, 'General'), (1, 'Trackdays/Experiences'), (2, 'Bookings'), (3, 'Other')], default=0, max_length=11)),
                ('message', models.TextField()),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contacted_on'],
            },
        ),
    ]
