# Generated by Django 3.2 on 2022-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='variant',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
